### ISSUE TITLE
Is there any difference between LSP-vue and LSP-volar?

### ISSUE THREAD

**Issue by AirBashX** [sublimelsp/LSP-volar#138]
Is there any difference between these two plugins?

**Comment by rchl** [comment]
LSP-vue is badly named (mistakes were made early on). It's actually supposed to be called `LSP-vetur`.

If you know the difference between Vetur and Volar then this should make more sense.

If you don't know the difference then the gist is:
 - Vetur is no longer maintained, has issues with latest typescript versions and is generally not recommended. *
 - Volar is actively maintained and generally the way to go but due to fast development pace and lack of proper testing, you should expect some things to break now and then (as they often did for me).

* If you are intending to use those with Vue 2 then Vetur might still be a more stable option. Volar is getting up there though and 1.x.x versions are quite good already (there is a [PR](https://github.com/sublimelsp/LSP-volar/pull/134) to update to 1.x but it's not yet merge).
